### ISSUE TITLE
Unable to select a time zone of choice.

### ISSUE THREAD

**Issue by daracloud** [true-while/mct-timer#2]
Thank you, Alex, for all your efforts at developing this solution. Is it possible to change the time zone? It looks like we are stuck with EST right now.

**Comment by jfbilodeau** [comment]
Thanks for the suggestion. I think we'll have an update soon to support timezones.

**Comment by true-while** [comment]
The Time Zone feature is implemented.

**Comment by true-while** [comment]
The Time Zone feature is implemented.

**Comment by true-while** [comment]
The Time Zone feature is implemented.
